Portfolio/Models/Home/HackerRank.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Portfolio.Models.Home
{
    public class HackerRank
    {
        public List<object> HR { get; set; }
    }
}

Portfolio/Models/Home/SendMail.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Portfolio.Models.Home
{
    public class SendMail
    {   [Required(AllowEmptyStrings =false,ErrorMessage ="Required Field*")]
        public string Firstname { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Required Field*")]
        public string LastName { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Required Field*")]
        public string From { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Required Field*")]
        public string To { get; set; }
        [DataType(DataType.PhoneNumber)]
        public string Phone { get; set; }
        [Required(AllowEmptyStrings =false,ErrorMessage ="Please write some message!")]
        public string Message { get; set; }
    }
}

Portfolio/Controllers/Home/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Portfolio.Enumeration;
using Portfolio.Models.Home;
using Portfolio.Common;
using System.Net.Mail;
using System.Net;
using System.Threading;
using System.IO;

namespace Portfolio.Controllers.Home
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Home()
        {
            return View();
        }
        public ActionResult About()
        {
            return View();
        }
        public ActionResult Resume()
        {
            return View();
        }
        public ActionResult Projects()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ContactMe(SendMail mail)
        {
           
                var tEmail = new Thread(() => SendMail(mail));
                tEmail.Start();
                return RedirectToAction("Home");
           
        }

        public FileResult DownLoad()
        {
            string fileName = Directory.GetFiles(Server.MapPath("~/App_Data"))[0].ToString();
            string contentType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
            return File(fileName, contentType, "Resume.docx");
        }

        public void SendMail(SendMail sendmail)
        {
            try
            {
                using (var mail = new MailMessage())
                {
                    const string email = "sendrj90029mail@gmail.com";
                    const string password = "Newpwd@123";

                    var loginInfo = new NetworkCredential(email, password);


                    mail.From = new MailAddress(sendmail.From);
                    mail.To.Add(new MailAddress(email));
                    mail.To.Add("rj90029@gmail.com");
                    mail.CC.Add(sendmail.From);
                    mail.Subject = sendmail.Firstname + " " + sendmail.LastName+" " + "Contacting";
                    mail.Body = sendmail.Message;
                    mail.IsBodyHtml = true;

                    try
                    {
                        using (var smtpClient = new SmtpClient(
                                                         "smtp.gmail.com", 587))
                        {
                            smtpClient.EnableSsl = true;
                            smtpClient.UseDefaultCredentials = false;
                            smtpClient.Credentials = loginInfo;
                            smtpClient.Send(mail);
                        }

                    }

                    finally
                    {
                        //dispose the client
                        mail.Dispose();
                    }

                }
            }
            catch (SmtpFailedRecipientsException ex)
            {
                foreach (SmtpFailedRecipientException t in ex.InnerExceptions)
                {
                    var status = t.StatusCode;
                    if (status == SmtpStatusCode.MailboxBusy ||
                        status == SmtpStatusCode.MailboxUnavailable)
                    {
                        Response.Write("Delivery failed - retrying in 5 seconds.");
                        System.Threading.Thread.Sleep(5000);
                        //resend
                        //smtpClient.Send(message);
                    }
                    else
                    {
                        Response.Write("Failed to deliver message to");
                    }
                }
            }
            catch (SmtpException Se)
            {
                // handle exception here
                Response.Write(Se.ToString());
            }

            catch (Exception ex)
            {
                Response.Write(ex.ToString());
            }
        }
        
    }
}

Portfolio/Controllers/Solutions/SolutionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Portfolio.Controllers.Solutions
{
    public class SolutionsController : Controller
    {
        // GET: Solutions
        public ActionResult Arrays_DS()
        {
            return View();
        }
        public ActionResult TwoDArrays_DS()
        {
            return View();
        }
        public ActionResult Dynamic_Array()
        {
            return View();
        }
        public ActionResult Left_Rotation()
        {
            return View();
        }
    }
}

Portfolio/Views/Home/About.cshtml
@{
  ViewBag.Title = "About";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    
    
    
</div>

Portfolio/Views/Home/Home.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    
</div>

Portfolio/Views/Home/Projects.cshtml
@{
    ViewBag.Title = "Projects";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4" style="font-family:Calibri">
            <h4>Let's walk through some of my projects</h4>
        </div>
        <div class="col-md-4"></div>
    </div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-2">
            <h3>verycoolrooms</h3>
        </div>
        <div class="col-md-8">
            •A hotel room booking website built on CMS(Mojo Portal)<br />
            <p><h4>Technologies Used:</h4></p>
            •ASP .Net(.aspx), MSSQL,JQuery,HTML,CSS,Ajax.
            <p><h4>My Contribution:</h4></p>
            <p>I was a part of 4 membered team where my job was to develop five(list, Add, Edit) screens.</p>
            <p>After development of screen i needed to do unit testing on screens.</p>
            <p>I was also responsible for doing peer review for my team members.</p>
            <p><h4>Website Link</h4></p>
            <a href="https://www.verycoolrooms.com" target="_blank">verycoolrooms.com</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-2"><h3>HRMS</h3></div>
        <div class="col-md-8">
            <p><h4>Human Resource Management System</h4></p>
            <p>A internal company website for Alligator Software India Pvt. Ltd. to manage it's employees.</p>
            <p><h4>Technologies Used:</h4></p>
            •ASP .Net MVC, MSSQL,JQuery,HTML,CSS,Ajax.
            <p><h4>My Contribution:</h4></p>
            <p>I was a part of 4 membered team where my job was to develop three(list, Add, Edit) screens.</p>
            <p>After development of screen i needed to do unit testing on screens and also work on design.</p>
            <p>I was also responsible for doing peer review for my team members.</p>
            <p>Beacause i was the senior member in the team so i was also helping my team members when they needed.</p>
            <p>Helped in implementing some unique requirements.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-2"><h3>Michuda Inc.</h3></div>
        <div class="col-md-8">
            <p>A mobile and web application built on Titanium Appcelerator to manage it's and contractor employees.</p>
            <p>This app was basically to manage employees work hours,meeting,trainings and projects.</p>
            <p><h4>Technologies Used:</h4></p>
            •Titanium(JavaScript),HTML,CSS,Ajax,MSSQL,SQLite and ASP .Net Web Services.
            <p><h4>My Contribution:</h4></p>
            <p>As part of three membered team i was responsible for implementing change requirements on existing app.</p>
            <p>In the absence of team lead i was also responsible for development and management of team member.</p>
            <p>I helped team in finishing the task on time when a hurdle in development was slowing down the workflow.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-2"><h3>Portfolio</h3></div>
        <div class="col-md-8">
            <p>A  web application built on MVC</p>
            <p>This application contains professional infomation about me and solutions to <a href="https://www.hackerrank.com" target="_blank">Hacker Rank</a> problems.</p>
            <p><h4>Technologies Used:</h4></p>
            •MVC,HTML,CSS,Bootstrap,Jquery.
            <p><h4>My Contribution:</h4></p>
            <p>I developed this whole application and also responsible for management of the site content.</p>
        </div>
    </div>
</div>

Portfolio/Views/Home/Resume.cshtml
@{
    ViewBag.Title = "Resume";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-2">
            <h4>
                <u>Education</u>
            </h4>
        </div>
        <div class="col-md-8">
            <p style="text-align:left">
                <h4>
                    B.Tech MIT, Muzaffarpur, Bihar. June 2015.
                </h4>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-2">
            <h4>
            </h4>
        </div>
        <div class="col-md-8">
            <p style="text-align:left">
                <h4>
                   Matriculation, Govt. Sarvodaya Co-Ed Vidyalaya with 83.4%.
                </h4>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-2">
            <h4></h4>
        </div>
        <div class="col-md-8">
            <p style="text-align:left">
                <h4>
                    Secondary Education, Govt. Sarvodaya Co-Ed Vidyalaya with 69%.
                </h4>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-3">
            <h4>
                <u>Relevant Coursework</u>
            </h4>
        </div>
        <div class="col-md-8">
           <p>
               Data Structure, Algorithm Designing, Object-Oriented Design, C# Programming,
               <br />
               Database Systems, Networking.
           </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-2">
            <h4>
                <u>Activities</u>
            </h4>
        </div>
        <div class="col-md-8">
            <p>
                •Co-Founded the Technical Club of the college that organized the 1st Technical Fest of the college.<br />
                •Successfully assisted the College Placement Cell in attracting twice as many companies during hiring season than those participated the last year.<br />
                •Served as a core member of the Planning Team at the college that organized its first ever Alumni Meet in over 10 years.<br />
                •Completed C# Certification from NIIT, Pitampura, New Delhi.
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-2">
            <h4>
                <u>Work</u>
            </h4>
        </div>
        <div class="col-md-8">
            <h2>
                Wipro Technologies(Nov, 2015- Oct, 2016)<br />
                Project Engineer
            </h2>
            <p>
                •Got trained in Wipro Tech. on Dot Net and scored 85% in evaluation test.<br />
                •After that worked on ASP Dot Net and created an online resume system, a website like Naukri.com<br />
                •Worked in support and maintenance of softwares.<br />
                •Worked in remote server monitoring.
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-2">
            <h4>
            </h4>
        </div>
        <div class="col-md-8">
            <h2>
                Alligator Software India Pvt. Ltd.(Oct, 2016- Now)<br />
                Sofware Engineer II
            </h2>
            <p>
                •Worked on MVC 4 and Content Management System.<br />
                •Proven experience on Titanium, Contributed in "Michuda Inc." mobile app.<br />
                •Implemented different dropdowns for Mobile and Desktop application of Michuda Inc.
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-2">
            <h4>Skills</h4>
        </div>
        <div class="col-md-8">
            <p><h3>Data Structure</h3></p>
            <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width:70%">
                    70%
                </div>
            </div>
            <p><h3>Algorithms</h3></p>
            <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:70%">
                    70%
                </div>
            </div>
            <p><h3>C#</h3></p>
            <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width:80%">
                    80%
                </div>
            </div>
            <p><h3>MVC</h3></p>
            <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width:80%">
                    80%
                </div>
            </div>
            <p><h3>Linq</h3></p>
            <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width:60%">
                    60%
                </div>
            </div>
            <p><h3>JQuery</h3></p>
            <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:70%">
                    70%
                </div>
            </div>
            <p><h3>Titanium</h3></p>
            <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width:60%">
                    60%
                </div>
            </div>
            <p><h3>CMS</h3></p>
            <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width:80%">
                   80% 
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <a href="https://drive.google.com/file/d/0B0y_BTwPg55reWhzOGJ5cDFtbzA/view?usp=sharing" target="_blank"><img src="~/Images/resume-button.png" /></a>
                </div>
            </div>
        </div>
    </div>
</div>

Portfolio/Views/Shared/_SolutionsLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="container">
        <div class="page-header">
            <div class="col-md-3">
            </div>
            <div class="col-md-1">
                @Html.ActionLink("Home", "Home", "Home")
            </div>
            <div class="col-md-1">
                @Html.ActionLink("About", "About", "Home")
            </div>
            <div class="col-md-1">
                @Html.ActionLink("Resume", "Resume", "Home")
            </div>
            <div class="col-md-1">
                @Html.ActionLink("Projects", "Projects", "Home")
            </div>
            <div class="col-md-1">
                @Html.ActionLink("HackerRank", "HackerRank", "Solutions")
            </div>
            <div class="col-md-2">
                Welcome To My Place
            </div>
            <div class="col-md-2">
            </div>
        </div>
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-2">
                <div class="col-md-6">
                    <img src="~/Images/nerd.png" />
                </div>
                <div class="col-md-4">
                    JUST AS<br />U WANT
                </div>
                <div class="col-md-2">

                </div>
            </div>
            <div class="col-md-4">
                <div style="color:chartreuse">
                    <h2>HackerRank Solutions</h2>
                </div>
            </div>
            <div class="col-md-4">
                @{
                    List<SelectListItem> listItems = new List<SelectListItem>();
                    listItems.Add(new SelectListItem
                    {
                        Text = "Data Structure",
                        Value = "0"
                    });
                    listItems.Add(new SelectListItem
                    {
                        Text = "Algorithms",
                        Value = "1"
                    });
                }
                @Html.DropDownList(listItems.ToString(), listItems, "--Select Subject--")
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
            </div>
            <div class="col-md-2">
                <div class="row">
                    <span>
                        <h4><b>Data Structures</b></h4>
                    </span>
                </div>
                <div class="row" ><h4>@Html.ActionLink("Arrays-DS", "Arrays_DS", "Solutions")</h4></div>
                <div class="row"><h4>@Html.ActionLink("2D Arrays-DS", "TwoDArrays_DS", "Solutions")</h4></div>
                <div class="row"><h4>@Html.ActionLink("Dynamic Array", "Dynamic_Array", "Solutions")</h4></div>
                <div class="row"><h4>@Html.ActionLink("Left Rotation", "Left_Rotation", "Solutions")</h4></div>
            </div>
            <div class="col-md-8">
                @RenderBody()
            </div>
        </div>
        <div class="panel-footer">
            <div class="col-md-4">
            </div>
            <div class="col-md-6">
                © Copyright 2017 Roshan Jha. Designed by Roshan Jha.
            </div>
            <div class="col-md-2">
            </div>
        </div>
    </div>
</body>
</html>

Portfolio/Views/Solutions/Arrays_DS.cshtml
@{
    Layout = "~/Views/Shared/_SolutionsLayout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Arrays-DS</title>
</head>
<body>
    <div class="row">
        <p>
            An array is a type of data structure that stores elements of the same type in a contiguous <br />
            block of memory.<br />
        </p>
        <p>
            In an array, A, of size N, each memory location has some unique index,  (where ), that can <br />
            be referenced as  (you may also see it written as ).<br />
        </p>
        <p>
            Given an array, A, of N integers, print each element in reverse order as a single line of <br />
            space-separated integers.<br />
        </p>
        <p>
            Input Format
        </p>
        <p>
            The first line contains an integer N,  (the number of integers in A).
        </p>
        <p>
            The second line contains N space-separated integers describing A.
        </p>
        <p>
            Constraints<br />
            <b>1<=N<=10^3</b><br />
            <b>1<=A[i]<=10^4, Where A[i] is ith integer in A.</b><br />
        </p>
        <p>
            <b>Output Format</b><br />
            Print all  integers in  in reverse order as a single line of space-separated integers.<br />
        </p>
        <p>
            <b>
                Sample Input<br />
                4<br />
                1 4 3 2<br />
                Sample Output<br />
                2 3 4 1<br />
            </b>
        </p>
    </div>
    <div class="row">
        <p>Solution Goes Here</p>
    </div>
    <div class="row">
    <pre class="col-md-10">
        <code>
            using System;
            using System.Collections.Generic;
            using System.IO;
            using System.Linq;
            class Solution {

                static void Main(String[] args) {
                int n = Convert.ToInt32(Console.ReadLine());
                string[] arr_temp = Console.ReadLine().Split(' ');
                int[] arr = Array.ConvertAll(arr_temp,Int32.Parse);
                //This is an inbuilt function.
                //One can iterate through the array in reverse as well.
                //Time complexity in both cases is <em><b>O(N)</b></em>
                //N is size of array.
                Array.Reverse(arr);
                Console.Write(string.Join(" ",arr));


                }
            }
        </code>
    </pre>
    </div>
</body>
</html>

Portfolio/Views/Solutions/Dynamic_Array.cshtml
@{
    ViewBag.Title = "Dynamic_Array";
    Layout = "~/Views/Shared/_SolutionsLayout.cshtml";
}
<div class="row">
    Create a list,seqList , of N empty sequences, where each sequence is indexed from 0 to<br />
    N-1. The elements within each of the N sequences also use 0-indexing.<br />
    <p>
        Create an integer,<em>lastAnswer</em> , and initialize it to <b>0</b>.
    </p>
    <p>
        The 2 types of queries that can be performed on your list of sequences (<em>seqList</em>) are<br />
        described below:
    </p>
    <code>Query:1 X y</code>
    <ol>
        <li>
            1. Find the sequence, <em>seq</em> at index <em>((x &oplus;lastAnswer)%N)</em> in <em>seqList</em> .
        </li>
        <li>
            Append integer <em>y</em> to sequence <em>seq</em>.
        </li>
    </ol>
    <code>Query:2 X y</code>
    <ol>
        <li>
            1. Find the sequence,<em>seq</em> , at index <em>((x &oplus; )%N)</em> in<em>seqList</em> .
        </li>
        <li>
            2. Find the value of element<em>y%size</em>  in <em>seq</em> (where <em>size</em> is the size of <em>seq</em>) and assign it<br />
            to <em>lastAnswer</em> .
        </li>
        <li>
            3. Print the new value of   <em>lastAnswer</em>  on a new line
        </li>
    </ol>
    <div class="row">
        <b>Task</b>
        Given N,Q and Q queries, execute each query.<br />
        <b>Note:</b>&oplus; is the bitwise XOR operation, which corresponds to the ^ operator in most languages. <br />
        <b>Input Format</b>
        <p>
            The first line contains two space-separated integers, N (the number of sequences) and  Q(the<br />
            number of queries), respectively.<br />
            Each of the <b>Q</b> subsequent lines contains a query in the format defined above.
        </p>
        <b>Constraints</b>
        <ol>
            <li>
                <b>1<=N,Q<=10^5</b>
            </li>
            <li>
                <b>
                    0<=x<=10^9
                </b>
            </li>
            <li>
                <b>
                    0<=y<=10^9
                </b>
            </li>
            <li>
                It is guaranteed that query type 2 will never query an empty sequence or index.
            </li>
        </ol>
    </div>
    <div>
        <p><b>Output Format</b></p>
        <p>For each type 2 query, print the updated value of  on a new line.</p>
    </div>
    <div class="row">
        <p><b>Sample Input</b></p>
        <pre>
            2 5
            1 0 5
            1 1 7
            1 0 3
            2 1 0
            2 1 1
        </pre>
        <p><b>Sample Output</b></p>
        <pre>
            7
            3
        </pre>
    </div>
    <div class="row">
        <p><b>Explanation</b></p>
        <p>
            Initial Values:<br />
            N = 2<br />
            <em>lastAnswer = 0</em><br />
            <em>S0 = []</em><br />
            <em>S1 = []</em><br />
        </p>
        <p>Query 0: Append 5 to sequence <em>((0 &oplus; 0)%2) = 0</em>. </p>
        <em>lastAnswer = 0</em><br />
        <em>S0 = [5]</em><br />
        <em>S1 = []</em><br />
        <p>Query 1: Append 7 to sequence <em>((1 &oplus; 0)%2) = 1</em></p>
        <em>S0 = [5]</em><br />
        <em>S1 = [7]</em><br />
        <p>Query 2: Append 3 to sequence <em>((0 &oplus; 0)%2) = 0</em></p>
        <em>lastAnswer = 0</em><br />
        <em>S0 = [5]</em><br />
        <em>S1 = [7]</em><br />
        <p>Query 3: Assign the value at index <b>0</b> of sequence <em>((1 &oplus; 0)%2) = 1</em> to <em>lastAnswer,</em> print<br />
        <em>lastAnswer</em></p>
        <em>lastAnswer = 7</em><br />
        <em>S0 = [5,3]</em><br />
        <em>S1 = [7]</em><br />
        <pre>7</pre>
        <p>
            Query 4: Assign the value at index <b>1</b> of sequence <em>((1 &oplus; 7)%2) = 0</em> to <em>lastAnswer,</em> print<br />
            <em>lastAnswer</em>
        </p>
        <em>lastAnswer = 7</em><br />
        <em>S0 = [5,3]</em><br />
        <em>S1 = [7]</em><br />
        <pre>3</pre>
    </div>
    <div class="row">
        <b>Solution Goes Here:</b>
         <p>
             <pre>
                using System;
                using System.Collections.Generic;
                using System.Collections;
                using System.IO;
                class Solution
                {
                    static void Main(String[] args)
                    {
                        string[] input = Console.ReadLine().Trim().Split(' ');
                        int N = Convert.ToInt32(input[0]);
                        int Q = Convert.ToInt32(input[1]);
        
                        List&lt;&lt;int&gt; seqN = new List&lt;&lt;int&gt;&gt;(N);
                        for(int i=0;i&lt;N;i++)
                        {
                            seqN.Add(new List&lt;int&gt;());
                        }
                        int LastAnswer = 0;
                        for(int i=0;i&lt;Q;i++)
                        {
                            string[] query = Console.ReadLine().Trim().Split(' ');
                            int[] arr = Array.ConvertAll(query,int.Parse);
                            int t = arr[0];
                            int x = arr[1];
                            int y = arr[2];
                            int seqIndex = ((x ^ LastAnswer ) % N);
                            List&lt;int&gt; currSeq = seqN[seqIndex];
                            if(t==1)
                            {
                                currSeq.Add(y);
                            }
                            else
                            {
                                LastAnswer = currSeq[y%currSeq.Count];
                                Console.WriteLine(LastAnswer);
                            }
                        }

                    }
                }
             </pre>
         </p>
    </div>
</div>

Portfolio/Views/Solutions/Left_Rotation.cshtml
<br />
@{
    ViewBag.Title = "Left_Rotation";
    Layout = "~/Views/Shared/_SolutionsLayout.cshtml";
}
<div class="row">
    <p>
        A left rotation operation on an array of size n shifts each of the array's elements 1 unit to the left. For example, if 2<br />
        left rotations are performed on array [1,2,3,4,5] , then the array would become [3,4,5,1,2].<br /><br />

        Given an array of n integers and a number, d, perform d left rotations on the array. Then print the updated array as a <br />
        single line of space-separated integers.<br />
        <br />
        <b>Input Format</b><br />

        The first line contains two space-separated integers denoting the respective values of n (the number of integers)<br />
        and d (the number of left rotations you must perform).<br />
        The second line contains n space-separated integers describing the respective elements of the array's initial state.<br />
        <br />
        <b>Constraints</b><br />
        <ul>
            <li>
                <b>1<=n<=10^5</b>
            </li>

            <li>
                <b>1<=d<=n</b>
            </li>
            <li>
                <b>1<=a[i]<=10^6</b>
            </li>
        </ul>
        <b>Output Format</b><br />
        Print a single line of n space-separated integers denoting the final state of the array after performing d left<br />
        rotations.<br />
        <b>Sample Input</b><br />
        <pre>
            5 4
            1 2 3 4 5
        </pre>
        <b>Sample Output</b><br />
        <pre>
           5 1 2 3 4
        </pre>
        <b>Explanation</b><br />
        When we perform  left rotations, the array undergoes the following sequence of changes:<br />
        <b>[1,2,3,4,5]-->[2,3,4,5,1]-->[3,4,5,1,2]-->[4,5,1,2,3]-->[5,1,2,3,4]</b><br />
        Thus, we print the array's final state as a single line of space-separated values, which is 5 1 2 3 4.<br />
    </p>
</div>
<div class="row">
    <pre>
    using System;
    using System.Collections.Generic;
    using System.IO;
    class Solution {
    static void Main(String[] args) {
        string[] input = Console.ReadLine().Trim().Split(' ');
        int[] arr = Array.ConvertAll(input, int.Parse);
        int N = arr[0];
        int d = arr[1];
        int[] initialArr = new int[N];
        string[] newarr = new string[N];
        int[] finalArr = new int[N];
        newarr = Console.ReadLine().Trim().Split(' ');
        initialArr = Array.ConvertAll(newarr,int.Parse);
        
        for(int i=0;i&lt;N;i++) {
            if(i&lt;d)
            {
                finalArr[N-d+i] = initialArr[i];
            }
            else
            {
                finalArr[i-d] = initialArr[i];;
            }
        }
        for(int i=0;i&lt;N;i++)
        {
            if(i==(N-1))
            {
                Console.Write(finalArr[i]);
            }
            else
            {
                Console.Write(finalArr[i].ToString()+" ");
            }

        }
    }
}
    </pre>
</div>